using Npgsql;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ShapePainter
{
    public static class DbHelper
    {
        private static readonly string dbName = "shapepainter_db";

        // Строка для подключения к системной базе, чтобы создать нашу
        private static readonly string systemConnStr = "Host=localhost;Username=postgres;Password=2005;Database=postgres";

        // Основная строка подключения к нашей целевой базе
        private static readonly string connStr = $"Host=localhost;Username=postgres;Password=2005;Database={dbName}";

        // Источник данных (убираем readonly, так как инициализируем его динамически)
        private static NpgsqlDataSource _ds = null!;

        // Объект для синхронизации потоков, чтобы избежать повторной инициализации
        private static readonly object _lock = new object();

        // Безопасный метод, который гарантирует, что к моменту работы с методами базы DataSource будет готов
        private static void EnsureDataSourceInitialized()
        {
            if (_ds == null)
            {
                lock (_lock)
                {
                    if (_ds == null)
                    {
                        // Сначала принудительно создаем структуру, если методы вызваны в обход CreateDbAsync
                        CreateDbRequiredStructure();

                        _ds = new NpgsqlDataSourceBuilder(connStr)
                            .MapEnum<ShapeType>("shape_type")
                            .Build();
                    }
                }
            }
        }

        public static async Task CreateDbAsync()
        {
            // Выносим создание базы и типов в синхронный гарантированный блок, 
            // чтобы Npgsql DataSource при создании сразу "увидел" готовый enum.
            await Task.Run(() =>
            {
                lock (_lock)
                {
                    CreateDbRequiredStructure();

                    if (_ds == null)
                    {
                        _ds = new NpgsqlDataSourceBuilder(connStr)
                            .MapEnum<ShapeType>("shape_type")
                            .Build();
                    }
                }
            });
        }

        // Внутренний метод, который подготавливает базу, тип enum и таблицы до инициализации DataSource
        private static void CreateDbRequiredStructure()
        {
            // 1. Сначала СИНХРОННО и изолированно проверяем/создаем БД на сервере
            EnsureDatabaseExists();

            // 2. Через обычный NpgsqlConnection (без пула DataSource) создаем enum и таблицы,
            // чтобы они гарантированно существовали ДО сканирования типов пулом _ds.
            using (var conn = new NpgsqlConnection(connStr))
            {
                conn.Open();

                var createEnumQuery = @"
                    DO $$ BEGIN
                        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shape_type') THEN
                            CREATE TYPE shape_type AS ENUM (
                                'rectangle'
                            );
                        END IF;
                    END $$;";

                var createTableQuery = @"
                    CREATE TABLE IF NOT EXISTS ""shape""(
                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        x DOUBLE PRECISION NOT NULL,
                        y DOUBLE PRECISION NOT NULL,
                        width DOUBLE PRECISION NOT NULL,
                        height DOUBLE PRECISION NOT NULL,
                        type shape_type NOT NULL DEFAULT 'rectangle',
                        PRIMARY KEY (id)
                    );";

                using (var cmd1 = new NpgsqlCommand(createEnumQuery, conn))
                {
                    cmd1.ExecuteNonQuery();
                }

                using (var cmd2 = new NpgsqlCommand(createTableQuery, conn))
                {
                    cmd2.ExecuteNonQuery();
                }
            }
        }

        private static void EnsureDatabaseExists()
        {
            // Используем обычный синхронный using и обычное подключение к базе 'postgres'
            // Это обходит ограничения пула и гарантирует выполнение команды CREATE DATABASE
            using (var conn = new NpgsqlConnection(systemConnStr))
            {
                conn.Open();

                // Проверяем, существует ли база данных в системном каталоге
                var checkDbQuery = "SELECT COUNT(*) FROM pg_database WHERE datname = @dbName;";
                using (var checkCmd = new NpgsqlCommand(checkDbQuery, conn))
                {
                    checkCmd.Parameters.AddWithValue("@dbName", dbName);
                    long count = (long)(checkCmd.ExecuteScalar() ?? 0L);

                    // Если базы нет (count == 0) — создаем её сессионно
                    if (count == 0)
                    {
                        using (var createCmd = new NpgsqlCommand($"CREATE DATABASE \"{dbName}\";", conn))
                        {
                            createCmd.ExecuteNonQuery();
                        }
                    }
                }
            }

            // Очищаем кэш пулов Npgsql, чтобы драйвер перечитал список баз на сервере
            NpgsqlConnection.ClearAllPools();
        }

        public static async Task<List<DbShape>> GetShapesAsync()
        {
            EnsureDataSourceInitialized();

            var shapes = new List<DbShape>();
            var query = "SELECT id, x, y, width, height, type FROM \"shape\" ORDER BY id;";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await using var reader = await cmd.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                shapes.Add(new DbShape()
                {
                    Id = reader.GetInt64(0),
                    X = reader.GetDouble(1),
                    Y = reader.GetDouble(2),
                    Width = reader.GetDouble(3),
                    Height = reader.GetDouble(4),
                    Type = reader.GetFieldValue<ShapeType>(5)
                });
            }
            return shapes;
        }

        public static async Task AddShapeAsync(DbShape shape)
        {
            EnsureDataSourceInitialized();

            var query = "INSERT INTO \"shape\" (x, y, width, height, type) VALUES (@X, @Y, @Width, @Height, @Type) RETURNING id;";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);

            cmd.Parameters.AddWithValue("@X", shape.X);
            cmd.Parameters.AddWithValue("@Y", shape.Y);
            cmd.Parameters.AddWithValue("@Width", shape.Width);
            cmd.Parameters.AddWithValue("@Height", shape.Height);

            // Указываем имя типа перечисления из PostgreSQL ("shape_type")
            cmd.Parameters.Add(new NpgsqlParameter("@Type", shape.Type) { DataTypeName = "shape_type" });

            long? id = (long?)await cmd.ExecuteScalarAsync();
            shape.Id = id ?? 0L;
        }

        public static async Task ClearAllShapesAsync()
        {
            EnsureDataSourceInitialized();

            var query = "TRUNCATE TABLE \"shape\" RESTART IDENTITY;";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await cmd.ExecuteNonQueryAsync();
        }
    }
}