using Npgsql;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ShapePainter
{
    public static class DbHelper
    {
        private static readonly string dbName = "shapepainter_db";
        private static readonly string systemConnStr = "Host=localhost;Username=postgres;Password=2005;Database=postgres";
        private static readonly string connStr = $"Host=localhost;Username=postgres;Password=2005;Database={dbName}";

        private static NpgsqlDataSource _ds = null!;

        public static async Task CreateDbAsync()
        {
            // 1. Проверяем и создаем саму базу данных через системное подключение
            await EnsureDatabaseExistsAsync();

            // 2. Инициализируем основной источник данных с маппингом ENUM
            if (_ds == null)
            {
                _ds = new NpgsqlDataSourceBuilder(connStr)
                    .MapEnum<ShapeType>("shape_type")
                    .Build();
            }

            // 3. Создаем типы и таблицы внутри нашей БД
            var createEnumQuery = @"
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shape_type') THEN
                        CREATE TYPE shape_type AS ENUM (
                            'rectangle'
                        );
                    END IF;
                END $$;";

            var createTableQuery = @"
                CREATE TABLE IF NOT EXISTS ""shape""(
                    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    x DOUBLE PRECISION NOT NULL,
                    y DOUBLE PRECISION NOT NULL,
                    width DOUBLE PRECISION NOT NULL,
                    height DOUBLE PRECISION NOT NULL,
                    type shape_type NOT NULL DEFAULT 'rectangle',
                    PRIMARY KEY (id)
                );";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();

            await using var cmd1 = new NpgsqlCommand(createEnumQuery, conn);
            await cmd1.ExecuteNonQueryAsync();

            await using var cmd2 = new NpgsqlCommand(createTableQuery, conn);
            await cmd2.ExecuteNonQueryAsync();
        }

        private static async Task EnsureDatabaseExistsAsync()
        {
            bool dbExists = false;

            // Используем отдельное подключение к системной базе
            await using (var conn = new NpgsqlConnection(systemConnStr))
            {
                await conn.OpenAsync();

                var checkDbQuery = "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = @dbName);";
                await using (var checkCmd = new NpgsqlCommand(checkDbQuery, conn))
                {
                    checkCmd.Parameters.AddWithValue("@dbName", dbName);
                    dbExists = (bool)(await checkCmd.ExecuteScalarAsync() ?? false);
                }

                // Если базы данных нет — смачно её создаем
                if (!dbExists)
                {
                    var createDbQuery = $"CREATE DATABASE \"{dbName}\";";
                    await using (var createCmd = new NpgsqlCommand(createDbQuery, conn))
                    {
                        await createCmd.ExecuteNonQueryAsync();
                    }
                }
            }

            // Если база создавалась с нуля, принудительно очищаем пулы, чтобы Npgsql перечитал состояние сервера
            if (!dbExists)
            {
                NpgsqlConnection.ClearAllPools();
            }
        }

        public static async Task<List<DbShape>> GetShapesAsync()
        {
            var shapes = new List<DbShape>();
            var query = "SELECT id, x, y, width, height, type FROM \"shape\" ORDER BY id;";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await using var reader = await cmd.ExecuteReaderAsync();

            while (await reader.ReadAsync())
            {
                shapes.Add(new DbShape()
                {
                    Id = reader.GetInt64(0),
                    X = reader.GetDouble(1),
                    Y = reader.GetDouble(2),
                    Width = reader.GetDouble(3),
                    Height = reader.GetDouble(4),
                    Type = reader.GetFieldValue<ShapeType>(5)
                });
            }
            return shapes;
        }

        public static async Task AddShapeAsync(DbShape shape)
        {
            var query = "INSERT INTO \"shape\" (x, y, width, height, type) VALUES (@X, @Y, @Width, @Height, @Type) RETURNING id;";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);

            cmd.Parameters.AddWithValue("@X", shape.X);
            cmd.Parameters.AddWithValue("@Y", shape.Y);
            cmd.Parameters.AddWithValue("@Width", shape.Width);
            cmd.Parameters.AddWithValue("@Height", shape.Height);
            cmd.Parameters.AddWithValue("@Type", shape.Type);

            long? id = (long?)await cmd.ExecuteScalarAsync();
            shape.Id = id ?? 0L;
        }

        public static async Task ClearAllShapesAsync()
        {
            var query = "TRUNCATE TABLE \"shape\" RESTART IDENTITY;";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await cmd.ExecuteNonQueryAsync();
        }
    }
}